import React, { useState } from 'react';
import { 
  Award, 
  CheckCircle2, 
  AlertCircle, 
  ChevronDown, 
  ChevronUp, 
  Calendar, 
  Download, 
  RotateCcw, 
  Sparkles, 
  Flame, 
  ShieldAlert, 
  Star,
  Layers,
  ArrowRight,
  BookOpen
} from 'lucide-react';
import { FullDiagnosticReport } from '../types/interview';

interface DiagnosticScorecardProps {
  report: FullDiagnosticReport;
  onRetake: () => void;
  onOpenQuestionBank: () => void;
}

export const DiagnosticScorecard: React.FC<DiagnosticScorecardProps> = ({
  report,
  onRetake,
  onOpenQuestionBank,
}) => {
  const [expandedQuestionIdx, setExpandedQuestionIdx] = useState<number | null>(0);

  const getDecisionBadge = (decision: string) => {
    switch (decision) {
      case 'Strong Hire':
        return {
          bg: 'bg-emerald-500/20 border-emerald-500/40 text-emerald-300',
          glow: 'shadow-emerald-500/20',
          text: 'STRONG HIRE',
        };
      case 'Hire':
        return {
          bg: 'bg-indigo-500/20 border-indigo-500/40 text-indigo-300',
          glow: 'shadow-indigo-500/20',
          text: 'HIRE',
        };
      case 'Leaning Hire':
        return {
          bg: 'bg-blue-500/20 border-blue-500/40 text-blue-300',
          glow: 'shadow-blue-500/20',
          text: 'LEANING HIRE',
        };
      case 'Leaning No Hire':
        return {
          bg: 'bg-amber-500/20 border-amber-500/40 text-amber-300',
          glow: 'shadow-amber-500/20',
          text: 'LEANING NO HIRE',
        };
      default:
        return {
          bg: 'bg-rose-500/20 border-rose-500/40 text-rose-300',
          glow: 'shadow-rose-500/20',
          text: 'STRONG NO HIRE',
        };
    }
  };

  const decisionBadge = getDecisionBadge(report.hiringDecision);

  // Download Report Text File
  const handleDownload = () => {
    const content = `=====================================================
PREPGENIUS AI - EXECUTIVE INTERVIEW SCORECARD
=====================================================
Date: ${report.sessionMetadata?.date || new Date().toLocaleDateString()}
Role: ${report.sessionMetadata?.seniority || ''} ${report.sessionMetadata?.role || 'Software Engineer'}
Company: ${report.sessionMetadata?.company || 'Target Tech Firm'}
Duration: ${report.sessionMetadata?.durationMinutes || 10} minutes

-----------------------------------------------------
FINAL HIRING DECISION: ${report.hiringDecision.toUpperCase()}
OVERALL SCORE: ${report.overallScore} / 100
-----------------------------------------------------
EXECUTIVE SUMMARY:
${report.decisionSummary}

TOP CANDIDATE SUPERPOWER:
${report.topSuperpower}

CRITICAL BLINDSPOT TO ADDRESS:
${report.criticalBlindspot}

-----------------------------------------------------
COMPETENCY DIMENSIONS:
- Technical Depth: ${report.competencyScores.technicalDepth.score}% (${report.competencyScores.technicalDepth.summary})
- Communication & Structure: ${report.competencyScores.communicationStructure.score}% (${report.competencyScores.communicationStructure.summary})
- Problem Solving & Tradeoffs: ${report.competencyScores.problemSolvingTradeoffs.score}% (${report.competencyScores.problemSolvingTradeoffs.summary})
- Impact & Execution: ${report.competencyScores.impactAndExecution.score}% (${report.competencyScores.impactAndExecution.summary})
- Leadership & Fit: ${report.competencyScores.leadershipAndFit.score}% (${report.competencyScores.leadershipAndFit.summary})

-----------------------------------------------------
QUESTION-BY-QUESTION BREAKDOWN:
${report.questionBreakdowns
  ?.map(
    (q, idx) => `
[Q${idx + 1}] ${q.questionText} (${q.targetCompetency})
Candidate Score: ${q.candidateScore}/100
Strengths:
${q.candidateStrengths?.map((s) => `  + ${s}`).join('\n')}
Gaps:
${q.candidateGaps?.map((g) => `  - ${g}`).join('\n')}
Exemplar Staff-Level Response:
"${q.exemplarAnswer}"
`
  )
  .join('\n')}

-----------------------------------------------------
7-DAY INTERVIEW READINESS ROADMAP:
${report.actionPlan
  ?.map(
    (a) => `Day ${a.day}: ${a.focus}
Task: ${a.task}
Key Takeaway: ${a.keyTakeaway}
`
  )
  .join('\n')}
=====================================================
Generated by PrepGenius AI Interview Preparation Agent
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `interview-scorecard-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8">
      {/* Hiring Decision Hero Card */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 relative overflow-hidden space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
                Hiring Committee Consensus
              </span>
              {report.sessionMetadata && (
                <span className="text-xs text-slate-500">• {report.sessionMetadata.company}</span>
              )}
            </div>
            <div className="flex items-center gap-3">
              <span
                className={`text-base sm:text-lg font-black px-4 py-1.5 rounded-full border shadow-lg ${decisionBadge.bg} ${decisionBadge.glow}`}
              >
                {decisionBadge.text}
              </span>
              <div className="flex items-baseline gap-1">
                <span className="text-3xl sm:text-4xl font-black text-white">{report.overallScore}</span>
                <span className="text-sm font-semibold text-slate-400">/ 100</span>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2.5 w-full sm:w-auto">
            <button
              onClick={handleDownload}
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-xs font-semibold text-slate-200 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Report</span>
            </button>
            <button
              onClick={onRetake}
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-md transition-colors"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>New Mock Session</span>
            </button>
          </div>
        </div>

        {/* Executive Consensus Statement */}
        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-1">
          <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-300 block">
            Executive Summary
          </span>
          <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
            {report.decisionSummary}
          </p>
        </div>

        {/* Superpower & Blindspot Highlights */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-2xl bg-emerald-950/20 border border-emerald-500/30 space-y-1.5">
            <div className="flex items-center gap-1.5 text-emerald-300 font-bold text-xs uppercase tracking-wider">
              <Sparkles className="w-4 h-4 text-emerald-400" />
              <span>Standout Candidate Superpower</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">{report.topSuperpower}</p>
          </div>

          <div className="p-4 rounded-2xl bg-rose-950/20 border border-rose-500/30 space-y-1.5">
            <div className="flex items-center gap-1.5 text-rose-300 font-bold text-xs uppercase tracking-wider">
              <ShieldAlert className="w-4 h-4 text-rose-400" />
              <span>Critical Blindspot to Address</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">{report.criticalBlindspot}</p>
          </div>
        </div>
      </div>

      {/* 5-Dimensional Competency Breakdown */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 space-y-6">
        <div className="flex items-center gap-3 pb-3 border-b border-slate-800">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/20 text-indigo-400 flex items-center justify-center font-bold text-sm">
            <Layers className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-base font-bold text-white">Competency Dimensions</h2>
            <p className="text-xs text-slate-400">Detailed signals across core Big-Tech evaluation pillars</p>
          </div>
        </div>

        <div className="space-y-4">
          {[
            {
              name: 'Technical Depth & Architecture',
              data: report.competencyScores.technicalDepth,
              color: 'from-blue-500 to-indigo-500',
            },
            {
              name: 'Communication & Structure (STAR)',
              data: report.competencyScores.communicationStructure,
              color: 'from-indigo-500 to-purple-500',
            },
            {
              name: 'Problem Solving & Tradeoff Analysis',
              data: report.competencyScores.problemSolvingTradeoffs,
              color: 'from-purple-500 to-pink-500',
            },
            {
              name: 'Impact & Measurable Execution',
              data: report.competencyScores.impactAndExecution,
              color: 'from-pink-500 to-rose-500',
            },
            {
              name: 'Leadership & Cultural Fit',
              data: report.competencyScores.leadershipAndFit,
              color: 'from-emerald-500 to-teal-500',
            },
          ].map((comp, idx) => (
            <div key={idx} className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800/80 space-y-2">
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold text-white">{comp.name}</span>
                <span className="font-bold text-indigo-300">{comp.data?.score || 0}%</span>
              </div>
              <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                <div
                  className={`h-full bg-gradient-to-r ${comp.color} rounded-full transition-all duration-700`}
                  style={{ width: `${comp.data?.score || 0}%` }}
                />
              </div>
              <p className="text-xs text-slate-400 leading-relaxed">{comp.data?.summary}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Question-by-Question Deep Dive */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 space-y-6">
        <div className="flex items-center gap-3 pb-3 border-b border-slate-800">
          <div className="w-8 h-8 rounded-lg bg-purple-500/20 text-purple-400 flex items-center justify-center font-bold text-sm">
            <Star className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-base font-bold text-white">Question-by-Question Diagnostic</h2>
            <p className="text-xs text-slate-400">Analysis of your responses with Staff-level exemplar rewrites</p>
          </div>
        </div>

        <div className="space-y-4">
          {report.questionBreakdowns?.map((q, idx) => {
            const isExpanded = expandedQuestionIdx === idx;
            return (
              <div
                key={idx}
                className="rounded-2xl border border-slate-800 bg-slate-900/50 overflow-hidden transition-all"
              >
                {/* Header row */}
                <button
                  type="button"
                  onClick={() => setExpandedQuestionIdx(isExpanded ? null : idx)}
                  className="w-full p-4 flex items-center justify-between gap-3 text-left hover:bg-slate-900/80 transition-colors"
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <span className="w-6 h-6 rounded-md bg-indigo-950 border border-indigo-800 text-indigo-300 flex items-center justify-center font-bold text-xs shrink-0">
                      Q{idx + 1}
                    </span>
                    <div className="min-w-0">
                      <h4 className="text-xs sm:text-sm font-semibold text-white truncate">
                        "{q.questionText}"
                      </h4>
                      <span className="text-[11px] text-slate-400">Target: {q.targetCompetency}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 shrink-0">
                    <span
                      className={`text-xs font-bold px-2.5 py-0.5 rounded-full border ${
                        q.candidateScore >= 80
                          ? 'text-emerald-300 bg-emerald-500/20 border-emerald-500/30'
                          : q.candidateScore >= 65
                          ? 'text-amber-300 bg-amber-500/20 border-amber-500/30'
                          : 'text-rose-300 bg-rose-500/20 border-rose-500/30'
                      }`}
                    >
                      {q.candidateScore}/100
                    </span>
                    {isExpanded ? (
                      <ChevronUp className="w-4 h-4 text-slate-400" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-slate-400" />
                    )}
                  </div>
                </button>

                {/* Expanded Details */}
                {isExpanded && (
                  <div className="p-5 pt-0 space-y-4 text-xs border-t border-slate-800/80 mt-2">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-3">
                      <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                        <span className="font-semibold text-emerald-400 flex items-center gap-1 text-[11px] uppercase tracking-wider">
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          <span>Candidate Strengths</span>
                        </span>
                        <ul className="space-y-1 text-slate-300 list-disc list-inside">
                          {q.candidateStrengths?.map((s, i) => (
                            <li key={i}>{s}</li>
                          ))}
                        </ul>
                      </div>

                      <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                        <span className="font-semibold text-amber-400 flex items-center gap-1 text-[11px] uppercase tracking-wider">
                          <AlertCircle className="w-3.5 h-3.5" />
                          <span>Areas for Improvement</span>
                        </span>
                        <ul className="space-y-1 text-slate-300 list-disc list-inside">
                          {q.candidateGaps?.map((g, i) => (
                            <li key={i}>{g}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    {/* Staff Exemplar Rewrite */}
                    <div className="p-4 rounded-xl bg-indigo-950/30 border border-indigo-500/30 space-y-1.5">
                      <div className="flex items-center gap-1.5 text-indigo-300 font-bold text-[11px] uppercase tracking-wider">
                        <Sparkles className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Staff/Principal-Level Exemplar Response</span>
                      </div>
                      <p className="text-slate-200 leading-relaxed italic bg-slate-950/60 p-3 rounded-lg border border-slate-800 font-mono text-[11px]">
                        "{q.exemplarAnswer}"
                      </p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* 7-Day Personalized Readiness Action Plan */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 space-y-6">
        <div className="flex items-center justify-between pb-3 border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-pink-500/20 text-pink-400 flex items-center justify-center font-bold text-sm">
              <Calendar className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">7-Day Interview Readiness Roadmap</h2>
              <p className="text-xs text-slate-400">Targeted daily drills based on your diagnostic blindspots</p>
            </div>
          </div>

          <button
            onClick={onOpenQuestionBank}
            className="hidden sm:flex items-center gap-1 text-xs text-indigo-400 hover:text-indigo-300 font-semibold"
          >
            <span>Practice in Question Bank</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-7 gap-3">
          {report.actionPlan?.map((item) => (
            <div
              key={item.day}
              className="p-3 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2 flex flex-col justify-between"
            >
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                  Day {item.day}
                </span>
                <h5 className="font-bold text-xs text-white mt-2 mb-1">{item.focus}</h5>
                <p className="text-[11px] text-slate-400 leading-snug">{item.task}</p>
              </div>
              <div className="pt-2 border-t border-slate-800/80 text-[10px] text-indigo-300 font-medium">
                Goal: {item.keyTakeaway}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
